In [1]:
import pandas as pd

In [2]:
df_run_times = pd.read_excel('../../data/raw/Run Times.xlsx')

In [3]:
df_run_times

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [4]:
df_run_times.dtypes

Name                       str
Run Time               float64
Warm Up Time            object
Location                   str
Run Date        datetime64[us]
Race Date       datetime64[us]
Rain                      bool
Fee                        str
dtype: object

In [5]:
df_run_times.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      str
 1   Run Time      5 non-null      float64
 2   Warm Up Time  5 non-null      object
 3   Location      5 non-null      str
 4   Run Date      5 non-null      datetime64[us]
 5   Race Date     5 non-null      datetime64[us]
 6   Rain          5 non-null      bool
 7   Fee           5 non-null      str
dtypes: bool(1), datetime64[us](2), float64(1), object(1), str(3)
memory usage: 417.0+ bytes

In [6]:
df_run_times.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [7]:
df_run_times.Fee = pd.to_numeric(df_run_times.Fee.str.replace('$', ''))

In [8]:
df_run_times.dtypes

Name                       str
Run Time               float64
Warm Up Time            object
Location                   str
Run Date        datetime64[us]
Race Date       datetime64[us]
Rain                      bool
Fee                    float64
dtype: object

In [9]:
pd.to_numeric(df_run_times['Warm Up Time'], errors='coerce')

0    3.5
1    3.5
2    NaN
3    2.2
4    2.0
Name: Warm Up Time, dtype: float64

In [10]:
df_run_times['Warm Up Time']

0      3.5
1      3.5
2    3 min
3      2.2
4        2
Name: Warm Up Time, dtype: object

In [11]:
df_run_times['Warm Up Time'] = pd.to_numeric(df_run_times['Warm Up Time'].astype('str').str.replace(' min', ''))

In [12]:
df_run_times.dtypes

Name                       str
Run Time               float64
Warm Up Time           float64
Location                   str
Run Date        datetime64[us]
Race Date       datetime64[us]
Rain                      bool
Fee                    float64
dtype: object

In [13]:
df_run_times.Rain.astype('int')

0    0
1    1
2    0
3    0
4    0
Name: Rain, dtype: int64

#Asignment - Converting Data Types

In [15]:
df_alarm_survey = pd.read_excel('../../data/raw/Alarm Survey Data.xlsx')

In [16]:
df_alarm_survey.head()

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3.0,active,3.0,1,5 stars
1,2,31,3.0,light,3.0,3,3 stars
2,3,18,0.0,light_activity,4.0,1,1 stars
3,4,42,4.0,active,4.0,1,4 stars
4,5,30,1.0,light_activity,1.0,4,3 stars

In [17]:
df_alarm_survey.dtypes

survey_id               int64
age                     int64
number_of_children    float64
activity_level            str
sleep_quality         float64
number_of_snoozes       int64
alarm_rating              str
dtype: object

In [20]:
df_alarm_survey.number_of_children = df_alarm_survey.number_of_children.astype('int')

In [22]:
df_alarm_survey.dtypes

survey_id               int64
age                     int64
number_of_children      int64
activity_level            str
sleep_quality         float64
number_of_snoozes       int64
alarm_rating              str
dtype: object

In [26]:
df_alarm_survey.alarm_rating = pd.to_numeric(df_alarm_survey.alarm_rating.str.replace(' stars', ''))

In [28]:
df_alarm_survey.head()

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3,active,3.0,1,5
1,2,31,3,light,3.0,3,3
2,3,18,0,light_activity,4.0,1,1
3,4,42,4,active,4.0,1,4
4,5,30,1,light_activity,1.0,4,3

In [29]:
df_alarm_survey.dtypes

survey_id               int64
age                     int64
number_of_children      int64
activity_level            str
sleep_quality         float64
number_of_snoozes       int64
alarm_rating            int64
dtype: object