In [243]:
import pandas as pd

In [244]:
df_run_times = pd.read_excel('../../data/raw/Run Times.xlsx')

In [245]:
df_run_times

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [246]:
df_run_times.dtypes

Name                       str
Run Time               float64
Warm Up Time            object
Location                   str
Run Date        datetime64[us]
Race Date       datetime64[us]
Rain                      bool
Fee                        str
dtype: object

In [247]:
df_run_times.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      str
 1   Run Time      5 non-null      float64
 2   Warm Up Time  5 non-null      object
 3   Location      5 non-null      str
 4   Run Date      5 non-null      datetime64[us]
 5   Race Date     5 non-null      datetime64[us]
 6   Rain          5 non-null      bool
 7   Fee           5 non-null      str
dtypes: bool(1), datetime64[us](2), float64(1), object(1), str(3)
memory usage: 417.0+ bytes

In [248]:
df_run_times.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [249]:
df_run_times.Fee = pd.to_numeric(df_run_times.Fee.str.replace('$', ''))

In [250]:
df_run_times.dtypes

Name                       str
Run Time               float64
Warm Up Time            object
Location                   str
Run Date        datetime64[us]
Race Date       datetime64[us]
Rain                      bool
Fee                    float64
dtype: object

In [251]:
pd.to_numeric(df_run_times['Warm Up Time'], errors='coerce')

0    3.5
1    3.5
2    NaN
3    2.2
4    2.0
Name: Warm Up Time, dtype: float64

In [252]:
df_run_times['Warm Up Time']

0      3.5
1      3.5
2    3 min
3      2.2
4        2
Name: Warm Up Time, dtype: object

In [253]:
df_run_times['Warm Up Time'] = pd.to_numeric(df_run_times['Warm Up Time'].astype('str').str.replace(' min', ''))

In [254]:
df_run_times.dtypes

Name                       str
Run Time               float64
Warm Up Time           float64
Location                   str
Run Date        datetime64[us]
Race Date       datetime64[us]
Rain                      bool
Fee                    float64
dtype: object

In [255]:
df_run_times.Rain.astype('int')

0    0
1    1
2    0
3    0
4    0
Name: Rain, dtype: int64

#Asignment - Converting Data Types

In [256]:
df_alarm_survey = pd.read_excel('../../data/raw/Alarm Survey Data.xlsx')

In [257]:
df_alarm_survey.head()

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3.0,active,3.0,1,5 stars
1,2,31,3.0,light,3.0,3,3 stars
2,3,18,0.0,light_activity,4.0,1,1 stars
3,4,42,4.0,active,4.0,1,4 stars
4,5,30,1.0,light_activity,1.0,4,3 stars

In [258]:
df_alarm_survey.dtypes

survey_id               int64
age                     int64
number_of_children    float64
activity_level            str
sleep_quality         float64
number_of_snoozes       int64
alarm_rating              str
dtype: object

In [259]:
df_alarm_survey.number_of_children = df_alarm_survey.number_of_children.astype('int')

In [260]:
df_alarm_survey.dtypes

survey_id               int64
age                     int64
number_of_children      int64
activity_level            str
sleep_quality         float64
number_of_snoozes       int64
alarm_rating              str
dtype: object

In [261]:
df_alarm_survey.alarm_rating = pd.to_numeric(df_alarm_survey.alarm_rating.str.replace(' stars', ''))

In [262]:
df_alarm_survey.head()

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3,active,3.0,1,5
1,2,31,3,light,3.0,3,3
2,3,18,0,light_activity,4.0,1,1
3,4,42,4,active,4.0,1,4
4,5,30,1,light_activity,1.0,4,3

In [263]:
df_alarm_survey.dtypes

survey_id               int64
age                     int64
number_of_children      int64
activity_level            str
sleep_quality         float64
number_of_snoozes       int64
alarm_rating            int64
dtype: object

## Cleaning missing data

In [264]:
df_students = pd.read_excel('../../data/raw/Student Grades.xlsx')

In [265]:
df_students.head()

  Student             Class      Year  Grade
0    Emma  Freshman Seminar  Freshman   86.0
1  Olivia  Freshman Seminar  Freshman   86.0
2    Noah  Freshman Seminar  Freshman   86.0
3  Sophia  Freshman Seminar  Freshman   87.0
4    Liam  Freshman Seminar  Freshman   90.0

In [266]:
df_students.tail()

    Student Class    Year  Grade
81      NaN   NaN     NaN    NaN
82  Bennett   NaN     NaN    NaN
83      NaN   EDA  Junior   84.0
84    Gavin   EDA  Senior    NaN
85   Calvin   NaN     NaN  100.0

In [267]:
df_students.info()

<class 'pandas.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  84 non-null     str
 1   Class    83 non-null     str
 2   Year     80 non-null     str
 3   Grade    82 non-null     float64
dtypes: float64(1), str(3)
memory usage: 2.8 KB

In [268]:
df_students.shape

(86, 4)

In [269]:
df_students.describe()

            Grade
count   82.000000
mean    85.707317
std     15.527346
min     45.000000
25%     81.000000
50%     85.000000
75%     90.000000
max    200.000000

In [270]:
import numpy as np

In [271]:
df_students.Year.value_counts()

Year
Freshman     35
Sophomore    24
Junior       20
Senior        1
Name: count, dtype: int64

In [272]:
df_students.Year.value_counts(dropna=False)

Year
Freshman     35
Sophomore    24
Junior       20
NaN           6
Senior        1
Name: count, dtype: int64

In [273]:
df_students.isna

<bound method DataFrame.isna of     Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman   86.0
1    Olivia  Freshman Seminar  Freshman   86.0
2      Noah  Freshman Seminar  Freshman   86.0
3    Sophia  Freshman Seminar  Freshman   87.0
4      Liam  Freshman Seminar  Freshman   90.0
..      ...               ...       ...    ...
81      NaN               NaN       NaN    NaN
82  Bennett               NaN       NaN    NaN
83      NaN               EDA    Junior   84.0
84    Gavin               EDA    Senior    NaN
85   Calvin               NaN       NaN  100.0

[86 rows x 4 columns]>

In [274]:
df_students.isna().sum()

Student    2
Class      3
Year       6
Grade      4
dtype: int64

In [275]:
df_students.isna().any(axis=1)

0     False
1     False
2     False
3     False
4     False
      ...
81     True
82     True
83     True
84     True
85     True
Length: 86, dtype: bool

In [276]:
df_students[df_students.isna().any(axis=1)]

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
81      NaN                        NaN     NaN    NaN
82  Bennett                        NaN     NaN    NaN
83      NaN                        EDA  Junior   84.0
84    Gavin                        EDA  Senior    NaN
85   Calvin                        NaN     NaN  100.0

In [277]:
df_students[df_students.isna().any(axis=1)].dropna(subset=['Student', 'Class'])

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
84    Gavin                        EDA  Senior    NaN

In [278]:
df_students.dropna(subset=['Student', 'Class'], inplace=True)

In [279]:
df_students.shape

(82, 4)

In [280]:
df_students[df_students.Grade.isna()]

   Student                      Class    Year  Grade
62  Landon  Exploratory Data Analysis  Junior    NaN
84   Gavin                        EDA  Senior    NaN

In [281]:
df_students.Grade.mean()

np.float64(85.55)

In [282]:
df_students.Grade = df_students.Grade.fillna(df_students.Grade.mean())

In [283]:
df_students.Grade

0     86.00
1     86.00
2     86.00
3     87.00
4     90.00
      ...
77    85.00
78    93.00
79    91.00
80    87.00
84    85.55
Name: Grade, Length: 82, dtype: float64

In [284]:
df_students[df_students.isna().any(axis=1)]

   Student             Class Year  Grade
7    Jacob  Freshman Seminar  NaN   88.0
8  William  Freshman Seminar  NaN   89.0
9    Ethan  Freshman Seminar  NaN   86.0

In [285]:
df_students[df_students.Class == 'Freshman Seminar']

     Student             Class      Year  Grade
0       Emma  Freshman Seminar  Freshman   86.0
1     Olivia  Freshman Seminar  Freshman   86.0
2       Noah  Freshman Seminar  Freshman   86.0
3     Sophia  Freshman Seminar  Freshman   87.0
4       Liam  Freshman Seminar  Freshman   90.0
5      Mason  Freshman Seminar  Freshman   90.0
6   Isabella  Freshman Seminar  Freshman   90.0
7      Jacob  Freshman Seminar       NaN   88.0
8    William  Freshman Seminar       NaN   89.0
9      Ethan  Freshman Seminar       NaN   86.0
10       Ava  Freshman Seminar  Freshman   88.0
11   Michael  Freshman Seminar  Freshman   88.0

In [286]:
df_students.loc[7, 'Year'] = 'Freshman'

In [287]:
df_students.Year = np.where(df_students.Year.isna(), 'Freshman', df_students.Year)

df_students

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman  86.00
1    Olivia  Freshman Seminar  Freshman  86.00
2      Noah  Freshman Seminar  Freshman  86.00
3    Sophia  Freshman Seminar  Freshman  87.00
4      Liam  Freshman Seminar  Freshman  90.00
..      ...               ...       ...    ...
77    Aaron               EDA    Junior  85.00
78  Charles               EDA    Junior  93.00
79   Connor               EDA    Junior  91.00
80    Riley               EDA    Junior  87.00
84    Gavin               EDA    Senior  85.55

[82 rows x 4 columns]

## Asignment - Missing Data

In [288]:
df_alarm_survey.head()

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3,active,3.0,1,5
1,2,31,3,light,3.0,3,3
2,3,18,0,light_activity,4.0,1,1
3,4,42,4,active,4.0,1,4
4,5,30,1,light_activity,1.0,4,3

In [289]:
df_alarm_survey.info()

<class 'pandas.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   int64
 3   activity_level      6433 non-null   str
 4   sleep_quality       6082 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   int64
dtypes: float64(1), int64(5), str(1)
memory usage: 351.9 KB

In [290]:
df_alarm_survey[df_alarm_survey.isna().any(axis=1)]

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
10,11,28,2,light_activity,NaN,3,4
18,19,38,2,lightly active,NaN,1,5
23,24,24,2,very active,NaN,1,5
26,27,25,2,lightly active,NaN,1,2
28,29,29,2,lightly active,NaN,1,2
...,...,...,...,...,...,...,...
6310,6311,30,2,very active,NaN,0,3
6319,6320,44,2,lightly active,NaN,0,3
6375,6309,32,3,light,NaN,0,3
6377,6311,30,2,very active,NaN,0,3
6386,6320,44,2,lightly active,NaN,0,3

In [291]:
df_alarm_survey.sleep_quality.value_counts(dropna=False)

sleep_quality
5.0    2721
4.0    2261
3.0     997
NaN     351
1.0     103
Name: count, dtype: int64

In [293]:
df_alarm_survey.sleep_quality.fillna(2)

0       3.0
1       3.0
2       4.0
3       4.0
4       1.0
       ...
6428    5.0
6429    4.0
6430    5.0
6431    5.0
6432    4.0
Name: sleep_quality, Length: 6433, dtype: float64

In [301]:
df_alarm_survey.sleep_quality.value_counts(dropna=False)

sleep_quality
5.0    2721
4.0    2261
3.0     997
2.0     351
1.0     103
Name: count, dtype: int64

In [300]:
df_alarm_survey.sleep_quality = df_alarm_survey.sleep_quality.fillna(2)