In [1]:
import pandas as pd

In [2]:
df_run_times = pd.read_excel('../../data/raw/Run Times.xlsx')

In [3]:
df_run_times

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [4]:
df_run_times.dtypes

Name                       str
Run Time               float64
Warm Up Time            object
Location                   str
Run Date        datetime64[us]
Race Date       datetime64[us]
Rain                      bool
Fee                        str
dtype: object

In [5]:
df_run_times.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 8 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Name          5 non-null      str
 1   Run Time      5 non-null      float64
 2   Warm Up Time  5 non-null      object
 3   Location      5 non-null      str
 4   Run Date      5 non-null      datetime64[us]
 5   Race Date     5 non-null      datetime64[us]
 6   Rain          5 non-null      bool
 7   Fee           5 non-null      str
dtypes: bool(1), datetime64[us](2), float64(1), object(1), str(3)
memory usage: 417.0+ bytes

In [6]:
df_run_times.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,$0.00
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,$0.00
2,Alexis,8.1209,3 min,“the gym”,2023-05-10 15:00:00,2023-06-01,False,$2.50
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,$0.00
4,David,6.8342,2,“gym”,2023-05-10 16:30:00,2023-06-15,False,$2.50

In [7]:
df_run_times.Fee = pd.to_numeric(df_run_times.Fee.str.replace('$', ''))

In [8]:
df_run_times.dtypes

Name                       str
Run Time               float64
Warm Up Time            object
Location                   str
Run Date        datetime64[us]
Race Date       datetime64[us]
Rain                      bool
Fee                    float64
dtype: object

In [9]:
pd.to_numeric(df_run_times['Warm Up Time'], errors='coerce')

0    3.5
1    3.5
2    NaN
3    2.2
4    2.0
Name: Warm Up Time, dtype: float64

In [10]:
df_run_times['Warm Up Time']

0      3.5
1      3.5
2    3 min
3      2.2
4        2
Name: Warm Up Time, dtype: object

In [11]:
df_run_times['Warm Up Time'] = pd.to_numeric(df_run_times['Warm Up Time'].astype('str').str.replace(' min', ''))

In [12]:
df_run_times.dtypes

Name                       str
Run Time               float64
Warm Up Time           float64
Location                   str
Run Date        datetime64[us]
Race Date       datetime64[us]
Rain                      bool
Fee                    float64
dtype: object

In [13]:
df_run_times.Rain.astype('int')

0    0
1    1
2    0
3    0
4    0
Name: Rain, dtype: int64

#Asignment - Converting Data Types

In [14]:
df_alarm_survey = pd.read_excel('../../data/raw/Alarm Survey Data.xlsx')

In [15]:
df_alarm_survey.head()

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3.0,active,3.0,1,5 stars
1,2,31,3.0,light,3.0,3,3 stars
2,3,18,0.0,light_activity,4.0,1,1 stars
3,4,42,4.0,active,4.0,1,4 stars
4,5,30,1.0,light_activity,1.0,4,3 stars

In [16]:
df_alarm_survey.dtypes

survey_id               int64
age                     int64
number_of_children    float64
activity_level            str
sleep_quality         float64
number_of_snoozes       int64
alarm_rating              str
dtype: object

In [17]:
df_alarm_survey.number_of_children = df_alarm_survey.number_of_children.astype('int')

In [18]:
df_alarm_survey.dtypes

survey_id               int64
age                     int64
number_of_children      int64
activity_level            str
sleep_quality         float64
number_of_snoozes       int64
alarm_rating              str
dtype: object

In [19]:
df_alarm_survey.alarm_rating = pd.to_numeric(df_alarm_survey.alarm_rating.str.replace(' stars', ''))

In [20]:
df_alarm_survey.head()

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3,active,3.0,1,5
1,2,31,3,light,3.0,3,3
2,3,18,0,light_activity,4.0,1,1
3,4,42,4,active,4.0,1,4
4,5,30,1,light_activity,1.0,4,3

In [21]:
df_alarm_survey.dtypes

survey_id               int64
age                     int64
number_of_children      int64
activity_level            str
sleep_quality         float64
number_of_snoozes       int64
alarm_rating            int64
dtype: object

## Cleaning missing data

In [22]:
df_students = pd.read_excel('../../data/raw/Student Grades.xlsx')

In [23]:
df_students.head()

  Student             Class      Year  Grade
0    Emma  Freshman Seminar  Freshman   86.0
1  Olivia  Freshman Seminar  Freshman   86.0
2    Noah  Freshman Seminar  Freshman   86.0
3  Sophia  Freshman Seminar  Freshman   87.0
4    Liam  Freshman Seminar  Freshman   90.0

In [24]:
df_students.tail()

    Student Class    Year  Grade
81      NaN   NaN     NaN    NaN
82  Bennett   NaN     NaN    NaN
83      NaN   EDA  Junior   84.0
84    Gavin   EDA  Senior    NaN
85   Calvin   NaN     NaN  100.0

In [25]:
df_students.info()

<class 'pandas.DataFrame'>
RangeIndex: 86 entries, 0 to 85
Data columns (total 4 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Student  84 non-null     str
 1   Class    83 non-null     str
 2   Year     80 non-null     str
 3   Grade    82 non-null     float64
dtypes: float64(1), str(3)
memory usage: 2.8 KB

In [26]:
df_students.shape

(86, 4)

In [27]:
df_students.describe()

            Grade
count   82.000000
mean    85.707317
std     15.527346
min     45.000000
25%     81.000000
50%     85.000000
75%     90.000000
max    200.000000

In [28]:
import numpy as np

In [29]:
df_students.Year.value_counts()

Year
Freshman     35
Sophomore    24
Junior       20
Senior        1
Name: count, dtype: int64

In [30]:
df_students.Year.value_counts(dropna=False)

Year
Freshman     35
Sophomore    24
Junior       20
NaN           6
Senior        1
Name: count, dtype: int64

In [31]:
df_students.isna

<bound method DataFrame.isna of     Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman   86.0
1    Olivia  Freshman Seminar  Freshman   86.0
2      Noah  Freshman Seminar  Freshman   86.0
3    Sophia  Freshman Seminar  Freshman   87.0
4      Liam  Freshman Seminar  Freshman   90.0
..      ...               ...       ...    ...
81      NaN               NaN       NaN    NaN
82  Bennett               NaN       NaN    NaN
83      NaN               EDA    Junior   84.0
84    Gavin               EDA    Senior    NaN
85   Calvin               NaN       NaN  100.0

[86 rows x 4 columns]>

In [32]:
df_students.isna().sum()

Student    2
Class      3
Year       6
Grade      4
dtype: int64

In [33]:
df_students.isna().any(axis=1)

0     False
1     False
2     False
3     False
4     False
      ...
81     True
82     True
83     True
84     True
85     True
Length: 86, dtype: bool

In [34]:
df_students[df_students.isna().any(axis=1)]

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
81      NaN                        NaN     NaN    NaN
82  Bennett                        NaN     NaN    NaN
83      NaN                        EDA  Junior   84.0
84    Gavin                        EDA  Senior    NaN
85   Calvin                        NaN     NaN  100.0

In [35]:
df_students[df_students.isna().any(axis=1)].dropna(subset=['Student', 'Class'])

    Student                      Class    Year  Grade
7     Jacob           Freshman Seminar     NaN   88.0
8   William           Freshman Seminar     NaN   89.0
9     Ethan           Freshman Seminar     NaN   86.0
62   Landon  Exploratory Data Analysis  Junior    NaN
84    Gavin                        EDA  Senior    NaN

In [36]:
df_students.dropna(subset=['Student', 'Class'], inplace=True)

In [37]:
df_students.shape

(82, 4)

In [38]:
df_students[df_students.Grade.isna()]

   Student                      Class    Year  Grade
62  Landon  Exploratory Data Analysis  Junior    NaN
84   Gavin                        EDA  Senior    NaN

In [39]:
df_students.Grade.mean()

np.float64(85.55)

In [40]:
df_students.Grade = df_students.Grade.fillna(df_students.Grade.mean())

In [41]:
df_students.Grade

0     86.00
1     86.00
2     86.00
3     87.00
4     90.00
      ...
77    85.00
78    93.00
79    91.00
80    87.00
84    85.55
Name: Grade, Length: 82, dtype: float64

In [42]:
df_students[df_students.isna().any(axis=1)]

   Student             Class Year  Grade
7    Jacob  Freshman Seminar  NaN   88.0
8  William  Freshman Seminar  NaN   89.0
9    Ethan  Freshman Seminar  NaN   86.0

In [43]:
df_students[df_students.Class == 'Freshman Seminar']

     Student             Class      Year  Grade
0       Emma  Freshman Seminar  Freshman   86.0
1     Olivia  Freshman Seminar  Freshman   86.0
2       Noah  Freshman Seminar  Freshman   86.0
3     Sophia  Freshman Seminar  Freshman   87.0
4       Liam  Freshman Seminar  Freshman   90.0
5      Mason  Freshman Seminar  Freshman   90.0
6   Isabella  Freshman Seminar  Freshman   90.0
7      Jacob  Freshman Seminar       NaN   88.0
8    William  Freshman Seminar       NaN   89.0
9      Ethan  Freshman Seminar       NaN   86.0
10       Ava  Freshman Seminar  Freshman   88.0
11   Michael  Freshman Seminar  Freshman   88.0

In [44]:
df_students.loc[7, 'Year'] = 'Freshman'

In [45]:
df_students.Year = np.where(df_students.Year.isna(), 'Freshman', df_students.Year)

df_students

    Student             Class      Year  Grade
0      Emma  Freshman Seminar  Freshman  86.00
1    Olivia  Freshman Seminar  Freshman  86.00
2      Noah  Freshman Seminar  Freshman  86.00
3    Sophia  Freshman Seminar  Freshman  87.00
4      Liam  Freshman Seminar  Freshman  90.00
..      ...               ...       ...    ...
77    Aaron               EDA    Junior  85.00
78  Charles               EDA    Junior  93.00
79   Connor               EDA    Junior  91.00
80    Riley               EDA    Junior  87.00
84    Gavin               EDA    Senior  85.55

[82 rows x 4 columns]

## Asignment - Missing Data

In [46]:
df_alarm_survey.head()

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3,active,3.0,1,5
1,2,31,3,light,3.0,3,3
2,3,18,0,light_activity,4.0,1,1
3,4,42,4,active,4.0,1,4
4,5,30,1,light_activity,1.0,4,3

In [47]:
df_alarm_survey.info()

<class 'pandas.DataFrame'>
RangeIndex: 6433 entries, 0 to 6432
Data columns (total 7 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   survey_id           6433 non-null   int64
 1   age                 6433 non-null   int64
 2   number_of_children  6433 non-null   int64
 3   activity_level      6433 non-null   str
 4   sleep_quality       6082 non-null   float64
 5   number_of_snoozes   6433 non-null   int64
 6   alarm_rating        6433 non-null   int64
dtypes: float64(1), int64(5), str(1)
memory usage: 351.9 KB

In [48]:
df_alarm_survey[df_alarm_survey.isna().any(axis=1)]

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
10,11,28,2,light_activity,NaN,3,4
18,19,38,2,lightly active,NaN,1,5
23,24,24,2,very active,NaN,1,5
26,27,25,2,lightly active,NaN,1,2
28,29,29,2,lightly active,NaN,1,2
...,...,...,...,...,...,...,...
6310,6311,30,2,very active,NaN,0,3
6319,6320,44,2,lightly active,NaN,0,3
6375,6309,32,3,light,NaN,0,3
6377,6311,30,2,very active,NaN,0,3
6386,6320,44,2,lightly active,NaN,0,3

In [49]:
df_alarm_survey.sleep_quality.value_counts(dropna=False)

sleep_quality
5.0    2721
4.0    2261
3.0     997
NaN     351
1.0     103
Name: count, dtype: int64

In [50]:
df_alarm_survey.sleep_quality.fillna(2)

0       3.0
1       3.0
2       4.0
3       4.0
4       1.0
       ...
6428    5.0
6429    4.0
6430    5.0
6431    5.0
6432    4.0
Name: sleep_quality, Length: 6433, dtype: float64

In [51]:
df_alarm_survey.sleep_quality.value_counts(dropna=False)

sleep_quality
5.0    2721
4.0    2261
3.0     997
NaN     351
1.0     103
Name: count, dtype: int64

In [52]:
df_alarm_survey.sleep_quality = df_alarm_survey.sleep_quality.fillna(2)

## Inconsistent Text & Typos

In [53]:
df_students.head()

  Student             Class      Year  Grade
0    Emma  Freshman Seminar  Freshman   86.0
1  Olivia  Freshman Seminar  Freshman   86.0
2    Noah  Freshman Seminar  Freshman   86.0
3  Sophia  Freshman Seminar  Freshman   87.0
4    Liam  Freshman Seminar  Freshman   90.0

In [55]:
df_students.Class.value_counts()

Class
Intro to Python              25
Intro to SQL                 20
Freshman Seminar             12
Exploratory Data Analysis    12
EDA                          12
Python                        1
Name: count, dtype: int64

In [59]:
df_students[df_students.Class.isin(['Exploratory Data Analysis', 'EDA'])]

      Student                      Class       Year   Grade
58     Evelyn  Exploratory Data Analysis  Sophomore   89.00
59       Jack  Exploratory Data Analysis  Sophomore   84.00
60       Ella  Exploratory Data Analysis  Sophomore  200.00
61      Chloe  Exploratory Data Analysis  Sophomore   87.00
62     Landon  Exploratory Data Analysis     Junior   85.55
63  Christian  Exploratory Data Analysis     Junior   77.00
64     Jordan  Exploratory Data Analysis     Junior   83.00
65   Jonathan  Exploratory Data Analysis     Junior   82.00
66       Levi  Exploratory Data Analysis     Junior   91.00
67   Victoria  Exploratory Data Analysis     Junior   90.00
68     Aubrey  Exploratory Data Analysis     Junior   83.00
69      Jaxon  Exploratory Data Analysis     Junior   64.00
70     Julian                        EDA     Junior   95.00
71      Grace                        EDA     Junior   77.00
72     Isaiah                        EDA     Junior   88.00
73    Cameron                        EDA     Junior   72.00
74        Eli                        EDA     Junior   92.00
75      Angel                        EDA     Junior   79.00
76       Zoey                        EDA     Junior   91.00
77      Aaron                        EDA     Junior   85.00
78    Charles                        EDA     Junior   93.00
79     Connor                        EDA     Junior   91.00
80      Riley                        EDA     Junior   87.00
84      Gavin                        EDA     Senior   85.55

In [61]:
df_students[df_students.Class.isin(['Intro to Python', 'Python'])]

      Student            Class      Year  Grade
12  Alexander  Intro to Python  Freshman   85.0
13      Logan  Intro to Python  Freshman   85.0
14      James  Intro to Python  Freshman   82.0
15     Daniel  Intro to Python  Freshman   85.0
16     Elijah  Intro to Python  Freshman   85.0
17   Benjamin  Intro to Python  Freshman   81.0
18        Mia  Intro to Python  Freshman   80.0
19        Mia           Python  Freshman   80.0
20     Jayden  Intro to Python  Freshman   82.0
21      Aiden  Intro to Python  Freshman   86.0
22    Matthew  Intro to Python  Freshman   87.0
23      Emily  Intro to Python  Freshman   78.0
24    Jackson  Intro to Python  Freshman   88.0
25      Lucas  Intro to Python  Freshman   77.0
26      David  Intro to Python  Freshman   74.0
27     Joseph  Intro to Python  Freshman   93.0
28    Abigail  Intro to Python  Freshman   89.0
29      Avery  Intro to Python  Freshman   79.0
30    Anthony  Intro to Python  Freshman   84.0
31      Dylan  Intro to Python  Freshman   84.0
32     Andrew  Intro to Python  Freshman   94.0
33     Carter  Intro to Python  Freshman   95.0
34     Samuel  Intro to Python  Freshman   83.0
35    Gabriel  Intro to Python  Freshman   82.0
36     Joshua  Intro to Python  Freshman   71.0
37       John  Intro to Python  Freshman   50.0

In [62]:
df_students.head()

  Student             Class      Year  Grade
0    Emma  Freshman Seminar  Freshman   86.0
1  Olivia  Freshman Seminar  Freshman   86.0
2    Noah  Freshman Seminar  Freshman   86.0
3  Sophia  Freshman Seminar  Freshman   87.0
4    Liam  Freshman Seminar  Freshman   90.0

In [64]:
df_students.Year.value_counts()

Year
Freshman     38
Sophomore    24
Junior       19
Senior        1
Name: count, dtype: int64

In [66]:
df_students.Grade.describe()

count     82.000000
mean      85.550000
std       15.443965
min       45.000000
25%       81.000000
50%       85.275000
75%       89.750000
max      200.000000
Name: Grade, dtype: float64

In [68]:
df_students[df_students.Grade > 100]

   Student                      Class       Year  Grade
60    Ella  Exploratory Data Analysis  Sophomore  200.0

In [71]:
df_students.Class.value_counts()

Class
Intro to Python              25
Intro to SQL                 20
Freshman Seminar             12
Exploratory Data Analysis    12
EDA                          12
Python                        1
Name: count, dtype: int64

In [72]:
df_students.Class = np.where(df_students.Class == 'EDA', 'Exploratory Data Analysis', df_students.Class)
df_students.Class.value_counts()

Class
Intro to Python              25
Exploratory Data Analysis    24
Intro to SQL                 20
Freshman Seminar             12
Python                        1
Name: count, dtype: int64

In [73]:
df_students.Class = np.where(df_students.Class == 'Python', 'Intro to Python', df_students.Class)
df_students.Class.value_counts()

Class
Intro to Python              26
Exploratory Data Analysis    24
Intro to SQL                 20
Freshman Seminar             12
Name: count, dtype: int64

In [75]:
df_students.Grade = np.where(df_students.Grade > 100, 100, df_students.Grade)
df_students.Grade.describe()

count     82.000000
mean      84.330488
std        8.824663
min       45.000000
25%       81.000000
50%       85.275000
75%       89.750000
max      100.000000
Name: Grade, dtype: float64

In [76]:
df_grades = pd.read_excel('../../data/raw/Student Grades.xlsx')
df_grades.head()

  Student             Class      Year  Grade
0    Emma  Freshman Seminar  Freshman   86.0
1  Olivia  Freshman Seminar  Freshman   86.0
2    Noah  Freshman Seminar  Freshman   86.0
3  Sophia  Freshman Seminar  Freshman   87.0
4    Liam  Freshman Seminar  Freshman   90.0

In [77]:
df_grades.Class.value_counts()

Class
Intro to Python              25
Intro to SQL                 20
EDA                          13
Freshman Seminar             12
Exploratory Data Analysis    12
Python                        1
Name: count, dtype: int64

In [78]:
class_mappings = {
    'Intro to Python': 'Intro to Python',
    'Intro to SQL': 'Intro to SQL',
    'EDA': 'Exploratory Data Analysis',
    'Freshman Seminar': 'Freshman Seminar',
    'Exploratory Data Analysis': 'Exploratory Data Analysis',
    'Python': 'Intro to Python'
}

In [81]:
df_grades.Class = df_grades.Class.map(class_mappings)
df_grades.Class.value_counts()

Class
Intro to Python              26
Exploratory Data Analysis    25
Intro to SQL                 20
Freshman Seminar             12
Name: count, dtype: int64

In [82]:
df_run_times.head()

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,“school”,2023-04-15 12:00:00,2023-06-01,False,0.0
1,Alexis,10.3842,3.5,School,2023-04-22 12:30:00,2023-06-01,True,0.0
2,Alexis,8.1209,3.0,“the gym”,2023-05-10 15:00:00,2023-06-01,False,2.5
3,David,7.2123,2.2,“school”,2023-05-01 15:15:00,2023-06-15,False,0.0
4,David,6.8342,2.0,“gym”,2023-05-10 16:30:00,2023-06-15,False,2.5

In [89]:
df_run_times.Location = df_run_times.Location.str.lower().str.replace('the ', '').str.strip('“”')

In [90]:
df_run_times

,Name,Run Time,Warm Up Time,Location,Run Date,Race Date,Rain,Fee
0,Alexis,9.2343,3.5,school,2023-04-15 12:00:00,2023-06-01,False,0.0
1,Alexis,10.3842,3.5,school,2023-04-22 12:30:00,2023-06-01,True,0.0
2,Alexis,8.1209,3.0,gym,2023-05-10 15:00:00,2023-06-01,False,2.5
3,David,7.2123,2.2,school,2023-05-01 15:15:00,2023-06-15,False,0.0
4,David,6.8342,2.0,gym,2023-05-10 16:30:00,2023-06-15,False,2.5

## Asignment - Inconsisten Text & Typos

df_alarm_survey.head()

In [94]:
df_alarm_survey.head()

,survey_id,age,number_of_children,activity_level,sleep_quality,number_of_snoozes,alarm_rating
0,1,34,3,active,3.0,1,5
1,2,31,3,light,3.0,3,3
2,3,18,0,light_activity,4.0,1,1
3,4,42,4,active,4.0,1,4
4,5,30,1,light_activity,1.0,4,3

In [95]:
df_alarm_survey.describe()

,survey_id,age,number_of_children,sleep_quality,number_of_snoozes,alarm_rating
count,6433.000000,6433.000000,6433.000000,6433.000000,6433.000000,6433.000000
mean,3216.302192,29.069175,1.379761,4.110835,1.145811,2.955075
std,1856.007409,7.472048,1.388768,0.963415,1.599481,1.101363
min,1.000000,13.000000,0.000000,1.000000,0.000000,1.000000
25%,1609.000000,23.000000,0.000000,4.000000,0.000000,2.000000
50%,3217.000000,28.000000,1.000000,4.000000,0.000000,3.000000
75%,4825.000000,34.000000,2.000000,5.000000,2.000000,4.000000
max,6366.000000,47.000000,5.000000,5.000000,19.000000,5.000000

In [96]:
df_alarm_survey.number_of_children.value_counts()

number_of_children
0    2440
2    1498
1    1172
3     788
4     331
5     204
Name: count, dtype: int64

In [97]:
df_alarm_survey.activity_level.value_counts()

activity_level
active            2450
lightly active    2289
light_activity     691
very active        669
light              334
Name: count, dtype: int64

In [99]:
df_alarm_survey.activity_level = np.where(df_alarm_survey.activity_level.isin(['light_activity', 'light']) , 'lightly active', df_alarm_survey.activity_level)
df_alarm_survey.activity_level.value_counts()

activity_level
lightly active    3314
active            2450
very active        669
Name: count, dtype: int64