In [2]:
import pandas as pd

In [4]:
pd.read_csv('../../data/raw/course_offerings.csv')

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [9]:
pd.read_excel('../../data/raw/Course Offerings.xlsx', sheet_name=1)

   Course ID                  Course Name    Instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [10]:
import sqlite3

In [11]:
conn = sqlite3.connect('../../data/raw/maven.db')

In [12]:
pd.read_sql('SELECT * FROM courses', conn)

   course_id                       course    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

##Exploring a Dataframe

In [13]:
df = pd.read_csv('../../data/raw/course_offerings.csv')

In [14]:
df

   course_id                  course_name    instructor
0        101              Intro to Python  Chris Bruehl
1        102                 Intro to SQL   John Pauler
2        201    Exploratory Data Analysis    Alice Zhao
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [15]:
df.head(2)

   course_id      course_name    instructor
0        101  Intro to Python  Chris Bruehl
1        102     Intro to SQL   John Pauler

In [16]:
df.tail(2)

   course_id                  course_name    instructor
3        301                   Algorithms  Chris Bruehl
4        331  Natural Language Processing    Alice Zhao

In [17]:
df.shape

(5, 3)

In [18]:
df.count()

course_id      5
course_name    5
instructor     5
dtype: int64

In [20]:
df.describe()

        course_id
count    5.000000
mean   207.200000
std    107.829495
min    101.000000
25%    102.000000
50%    201.000000
75%    301.000000
max    331.000000

In [21]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 3 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   course_id    5 non-null      int64
 1   course_name  5 non-null      str
 2   instructor   5 non-null      str
dtypes: int64(1), str(2)
memory usage: 252.0 bytes