# Preparing for Modelling

In [1]:
import pandas as pd

ca = pd.read_csv('../../data/raw/happiness_data_ca.txt')
mx = pd.read_csv('../../data/raw/happiness_data_mx.txt')
us = pd.read_csv('../../data/raw/happiness_data_us.txt')
cr = pd.read_csv('../../data/raw/happiness_data_cr.txt')

## Apendd

In [2]:
# Canada data
ca.head()

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,Canada,2007,7.481753,NaN,0.930341,70.620003
2,Canada,2008,7.485604,0.938707,0.926315,70.680000
3,Canada,2009,7.487824,0.942845,0.915058,70.739998
4,Canada,2010,7.650346,0.953765,0.933949,70.800003

In [3]:
# Mexico data
mx.head()

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Mexico,2005,6.580658,0.902808,0.813745,64.400002
1,Mexico,2007,6.525378,0.878806,0.670430,64.680000
2,Mexico,2008,6.829036,0.876328,0.677477,64.820000
3,Mexico,2009,6.962819,0.868221,0.682463,64.959999
4,Mexico,2010,6.802389,0.876390,0.778121,65.099998

In [4]:
# US Data - falta la ultima columna
us.head()

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices
0,United States,2006,7.181794,0.964572,0.911496
1,United States,2007,7.512688,NaN,0.871904
2,United States,2008,7.280386,0.952587,0.877956
3,United States,2009,7.158032,0.911794,0.830684
4,United States,2010,7.163616,0.926159,0.828044

In [6]:
# Costa Rica data - priemra columna tiene un nombre diferente
cr.head()

,nombre del país,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Costa Rica,2006,7.082465,0.936938,0.882420,68.559998
1,Costa Rica,2007,7.432132,0.917678,0.922736,68.720001
2,Costa Rica,2008,6.850680,0.915759,0.912006,68.879997
3,Costa Rica,2009,7.614929,0.899782,0.886061,69.040001
4,Costa Rica,2010,7.271054,0.915141,0.881030,69.199997

In [14]:
pd.concat([ca, mx, us, cr.rename(columns={'nombre del país':'country_name'})]).reset_index(drop=True)

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
0,Canada,2005,7.418048,0.961552,0.957306,70.500000
1,Canada,2007,7.481753,NaN,0.930341,70.620003
2,Canada,2008,7.485604,0.938707,0.926315,70.680000
3,Canada,2009,7.487824,0.942845,0.915058,70.739998
4,Canada,2010,7.650346,0.953765,0.933949,70.800003
...,...,...,...,...,...,...
59,Costa Rica,2017,7.225182,0.921697,0.935618,70.000000
60,Costa Rica,2018,7.141075,0.875872,0.941888,70.000000
61,Costa Rica,2019,6.997619,0.906077,0.926830,70.000000
62,Costa Rica,2020,6.338472,0.834200,0.889400,70.000000
63,Costa Rica,2021,6.408448,0.876052,0.886652,70.000000

## Joining - Merge

In [15]:
sales_may = pd.read_excel('../../data/raw/Sales Tables.xlsx', sheet_name=0)
sales_june = pd.read_excel('../../data/raw/Sales Tables.xlsx', sheet_name=1)
regions = pd.read_excel('../../data/raw/Sales Tables.xlsx', sheet_name=2)

In [16]:
sales_may

        date  store  sales
0 2022-05-01      1    341
1 2022-05-01      2    291
2 2022-05-01      3    493
3 2022-05-01      4    428
4 2022-05-01      5    152

In [17]:
regions

   store region
0      2  North
1      3   East
2      4   West
3      8  South

In [19]:
(sales_may.merge(regions,
                 how='left',
                 left_on='store',
                 right_on='store'))

        date  store  sales region
0 2022-05-01      1    341    NaN
1 2022-05-01      2    291  North
2 2022-05-01      3    493   East
3 2022-05-01      4    428   West
4 2022-05-01      5    152    NaN

In [22]:
# cuando la columna que las relaciona tiene el mismo nombre
sales_may.merge(regions, how='left', on='store')

        date  store  sales region
0 2022-05-01      1    341    NaN
1 2022-05-01      2    291  North
2 2022-05-01      3    493   East
3 2022-05-01      4    428   West
4 2022-05-01      5    152    NaN

## Join Types

In [23]:
happy_scores = pd.concat([ca, mx, us, cr.rename(columns={'nombre del país':'country_name'})]).reset_index(drop=True)
happy_scores = happy_scores[happy_scores.year > 2019]
happy_scores.head()

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth
14,Canada,2020,7.024905,0.930611,0.886892,71.349998
15,Canada,2021,6.939435,0.926076,0.898229,71.400002
30,Mexico,2020,5.964221,0.778816,0.873347,65.800003
31,Mexico,2021,5.990751,0.778605,0.837159,65.800003
46,United States,2020,7.028088,0.937370,0.850447,NaN

In [47]:
pop = pd.read_excel('../../data/raw/List of countries and inhabited territories by total population. United Nations.xlsx')

#pop.groupby('Subregion')['Country'].count()
pop = pop[pop['UN statistical'] == 'Northern America']
pop

,Country or territory,Population,Population.1,Change,UN continental,UN statistical
23,Bermuda (United Kingdom),64749,64698,−0.08%,Americas,Northern America
36,Canada,38821259,39299105,0.0123,Americas,Northern America
81,Greenland (Denmark),54990,55922,0.0169,Americas,Northern America
181,Saint Pierre and Miquelon (France),5732,5681,−0.89%,Americas,Northern America
226,United States,341534046,343477335,0.0057,Americas,Northern America

In [49]:
happy_scores['country_name'] = happy_scores['country_name'].str.strip().str.lower()
pop['Country or territory'] = pop['Country or territory'].str.strip().str.lower()

In [50]:
(happy_scores.merge(pop, 
                    how='inner', 
                    left_on='country_name', 
                    right_on='Country or territory'))

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth,Country or territory,Population,Population.1,Change,UN continental,UN statistical
0,canada,2020,7.024905,0.930611,0.886892,71.349998,canada,38821259,39299105,0.0123,Americas,Northern America
1,canada,2021,6.939435,0.926076,0.898229,71.400002,canada,38821259,39299105,0.0123,Americas,Northern America
2,united states,2020,7.028088,0.937370,0.850447,NaN,united states,341534046,343477335,0.0057,Americas,Northern America
3,united states,2021,6.959088,0.920009,0.815735,NaN,united states,341534046,343477335,0.0057,Americas,Northern America

In [51]:
(happy_scores.merge(pop, 
                    how='outer', 
                    left_on='country_name', 
                    right_on='Country or territory'))

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth,Country or territory,Population,Population.1,Change,UN continental,UN statistical
0,NaN,NaN,NaN,NaN,NaN,NaN,bermuda (united kingdom),64749,64698,−0.08%,Americas,Northern America
1,canada,2020.0,7.024905,0.930611,0.886892,71.349998,canada,38821259,39299105,0.0123,Americas,Northern America
2,canada,2021.0,6.939435,0.926076,0.898229,71.400002,canada,38821259,39299105,0.0123,Americas,Northern America
3,costa rica,2020.0,6.338472,0.834200,0.889400,70.000000,NaN,NaN,NaN,NaN,NaN,NaN
4,costa rica,2021.0,6.408448,0.876052,0.886652,70.000000,NaN,NaN,NaN,NaN,NaN,NaN
5,NaN,NaN,NaN,NaN,NaN,NaN,greenland (denmark),54990,55922,0.0169,Americas,Northern America
6,mexico,2020.0,5.964221,0.778816,0.873347,65.800003,NaN,NaN,NaN,NaN,NaN,NaN
7,mexico,2021.0,5.990751,0.778605,0.837159,65.800003,NaN,NaN,NaN,NaN,NaN,NaN
8,NaN,NaN,NaN,NaN,NaN,NaN,saint pierre and miquelon (france),5732,5681,−0.89%,Americas,Northern America
9,united states,2020.0,7.028088,0.937370,0.850447,NaN,united states,341534046,343477335,0.0057,Americas,Northern America
10,united states,2021.0,6.959088,0.920009,0.815735,NaN,united states,341534046,343477335,0.0057,Americas,Northern America

In [52]:
(happy_scores.merge(pop, 
                    how='left', 
                    left_on='country_name', 
                    right_on='Country or territory'))

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth,Country or territory,Population,Population.1,Change,UN continental,UN statistical
0,canada,2020,7.024905,0.930611,0.886892,71.349998,canada,38821259,39299105,0.0123,Americas,Northern America
1,canada,2021,6.939435,0.926076,0.898229,71.400002,canada,38821259,39299105,0.0123,Americas,Northern America
2,mexico,2020,5.964221,0.778816,0.873347,65.800003,NaN,NaN,NaN,NaN,NaN,NaN
3,mexico,2021,5.990751,0.778605,0.837159,65.800003,NaN,NaN,NaN,NaN,NaN,NaN
4,united states,2020,7.028088,0.937370,0.850447,NaN,united states,341534046,343477335,0.0057,Americas,Northern America
5,united states,2021,6.959088,0.920009,0.815735,NaN,united states,341534046,343477335,0.0057,Americas,Northern America
6,costa rica,2020,6.338472,0.834200,0.889400,70.000000,NaN,NaN,NaN,NaN,NaN,NaN
7,costa rica,2021,6.408448,0.876052,0.886652,70.000000,NaN,NaN,NaN,NaN,NaN,NaN

In [53]:
(happy_scores.merge(pop, 
                    how='right', 
                    left_on='country_name', 
                    right_on='Country or territory'))

,country_name,year,happiness_score,social_support,freedom_to_make_life_choices,healthy_life_expectancy_at_birth,Country or territory,Population,Population.1,Change,UN continental,UN statistical
0,NaN,NaN,NaN,NaN,NaN,NaN,bermuda (united kingdom),64749,64698,−0.08%,Americas,Northern America
1,canada,2020.0,7.024905,0.930611,0.886892,71.349998,canada,38821259,39299105,0.0123,Americas,Northern America
2,canada,2021.0,6.939435,0.926076,0.898229,71.400002,canada,38821259,39299105,0.0123,Americas,Northern America
3,NaN,NaN,NaN,NaN,NaN,NaN,greenland (denmark),54990,55922,0.0169,Americas,Northern America
4,NaN,NaN,NaN,NaN,NaN,NaN,saint pierre and miquelon (france),5732,5681,−0.89%,Americas,Northern America
5,united states,2020.0,7.028088,0.937370,0.850447,NaN,united states,341534046,343477335,0.0057,Americas,Northern America
6,united states,2021.0,6.959088,0.920009,0.815735,NaN,united states,341534046,343477335,0.0057,Americas,Northern America